### ISSUE TITLE
Problem Installing VSS

### ISSUE THREAD

**Issue by rogermc2** [AdaCore/VSS#70]
Mac-Mini 2018
OSX 10.15.7
XCode 12.0

I have been using GNAT Studio successfully for sometime but, as it looks like being discontinued, I decided to try VSCode but have come up with a problem trying to install VSS. 
Spawn installed OK using alr but 
alr get vss resulted in 
Cloning into '/System/Volumes/Data/Ada_Source/vss_21.0.0_ded12078'... 
remote: Enumerating objects: 160, done. 
remote: Counting objects: 100% (160/160), done. 
remote: Compressing objects: 100% (67/67), done. 
remote: Total 2776 (delta 103), reused 122 (delta 92), pack-reused 2616 
Receiving objects: 100% (2776/2776), 562.66 KiB | 677.00 KiB/s, done. 
Resolving deltas: 100% (1708/1708), done. 
fatal: reference is not a tree: ded12078cfcaeb6c3c7fc1ffeea9e0d5cf4a1086 
error: Command ["git", "checkout", "-q", "ded12078cfcaeb6c3c7fc1ffeea9e0d5cf4a1086"] exited with code 128

**Comment by reznikmm** [comment]
Thank you for the report!

Indeed, we did something wrong, when we sent an alire crate to the alire index. We merged new version of the VSS into alire, so it should be fixed now.

**Comment by rogermc2** [comment]
I still get the problem
alr get vss           
Cloning into '/System/Volumes/Data/Ada_Source/vss_21.0.0_ded12078'...
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 2777 (delta 110), reused 139 (delta 102), pack-reused 2603
Receiving objects: 100% (2777/2777), 564.16 KiB | 356.00 KiB/s, done.
Resolving deltas: 100% (1707/1707), done.
fatal: reference is not a tree: ded12078cfcaeb6c3c7fc1ffeea9e0d5cf4a1086
error: Command ["git", "checkout", "-q", "ded12078cfcaeb6c3c7fc1ffeea9e0d5cf4a1086"] exited with code 128

This before and after upgrading alire to version1.0

**Comment by reznikmm** [comment]
@rogermc2, you need to update alire index somehow. I did this:

    alr init --lib aaa
    cd aaa/
    alr update --online

After that `alr get --build vss` works fine for me. I'm sure there are other ways to update the alire index, to be investigated.

**Comment by rogermc2** [comment]
Thanks
I used my existing spawn directory to do the update:
cd spawn_1.0.0_a3d12d2d 
alr update --online 
cd ..
alr get --build vss

This worked, concluding with:
vss=22.0.0-20210224 successfully retrieved and built.
There are no dependencies.
